language: python

python:
  - 3.12.9

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls

# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: "V4BaNHzcI1RTfr6rQ6Nei9oWG+WKB4QuEMjoTmeiXd/hYRQeGuWNBpkRMbLoyGCukpypdPYDOMp4+O6aZ2BUiA07R6kDFz3teSOspWUjxxyg5sxF+Flvro/lxxhrx2RbUBO6Y5yzUS3cX1Vkg9ATZphXE2ba7APJOPtD7/8YIYfIRw6M/hCDiqmc5hth86bQnWCuen5fVWzURUE0tTIK5CshcOvZeSSbLevT1jZ1GN7TTXKM+4dSmNVf2nhQmDgAPrFWoZfdE8dQn5L4TxZQAUyDPU3wJlQBVjqPSEeZLqJ6m4fm/6XAgBrGzsDazRgbRP9HGfOywtuQkTLiIjOgD2kv0uC45jd+7f5fI6EiLv69x7RLQG6KJfkcASfCbRh63vNOp75uYdheM4Hx3v5V0/nrt7107zm5BkCflEMTolD9pSPEQtM0lCP/08gKUmHgOSxjgcSsxmb9aMCnVb20l+6VyR0r0oHWlto/bs260dqWUbSRyA4Uau1IWPG+PngXqlrWuWaTeQl3noVcNe5cZhkWxB2vP3Fql4IxJouSiEPmXtrbq8jGAUe50UTyFEIh6vchfScGJRukA3K8/bvLKWMw9FO59P0RzRN03eKPlnzMUgb/Uk1/xyNrQEzmqSf6Z86IUgc5WEhR8sdbUQ7oC6Ewp00Z0ZMy6ZAJekuzMCI="
#   secret_access_key:
#     secure: "EmS1fiQnI7HTwgU5jVuXiX6B480sIQ5f57ZFs7wI9Pxs4I99LldC2hEbdA/Ex4CT3kLqsHJH2Yh08XHCbAuPnAnLq6Vf92Ud9zbAPbO6vYBwpyiD8zr0emKKLlyz967rhcHgqseH+M9nNB/TySJ+cZ16Lh+N0Ptau68pV+tSuSfgaQylcXgXoQJPZME3tDN9OFhWbcvMvW5nLg4S/keRla92NQW1GuuwEm16Fmdi336YurcwQgiUho7s0IrcDHE1+9ba16lWN0rOM3z6XsHM3v07fKG0KRWE2Wg8QiYa4bAg06/hxpLoVd2oAoDpDl2g46AGX35fuEZLqAFLzheAtBBlQ2pE2fRcR0jr4vV9rpXgdfnHeH+qbnYWnmPckF5s44qoNgHqLeqCV8Uwnn93it+7apYC3AqetLJ6u+UxhBrBxszx3Rw0Frn+Knin7DfSbs7x83jKiYbMY4OtFT0+6YEwXRFnYjbWfCBuBHM8q+ckPNTPXePQX7IR1/03/oKGtMgfBOPjTISC/pWK7gCQBxL7lX5neO7+SHUn67yKJnZ9MrCQ3/rpv0+6Cb7qFsbKy6Ktx3QSBxIPU6hBrN8mhpuHLoYxX6ZBqr5aJ4Ots8SmwzfnEFa8oG56ZHgF/Q5oDGbUj1VTVqjF2Q6fIMAa7mvoufbajfKB963w4dQdQCU="
#   region: "us-east-1"
#   app: "django-tutorial"
#   env: "Django-tutorial-env"
#   bucket_name: "elasticbeanstalk-us-east-1-559050211896"